dist: xenial
language: python
cache: pip
python:
- '3.6'
branches:
  only:
  - "/.*/"
addons:
  apt:
    packages:
    - pandoc
install:
- pandoc -v
- pip install -r requirements.txt
script:
- echo "Hello"
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: bash _scripts/push_to_wiki.sh
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_0a73d3c4e754_key -iv $encrypted_0a73d3c4e754_iv
  -in deploy_rsa.enc -out deploy_rsa -d
