dist: xenial
sudo: false
language: python
cache: pip
python:
  # Use the default version that they give us because why not
  - '3.6'
branches:
  only:
  - "/.*/"
addons:
  apt:
    packages:
    - pandoc
install:
  - pandoc -v
  - pip install -r requirements.txt
script:
  - git checkout -b deploy
  - echo 1 #test $TRAVIS_BRANCH = "deploy" && bash _scripts/rebuild_branch.sh
  - test $TRAVIS_BRANCH = "master" && bash _scripts/push_to_wiki.sh ${GITHUB_TOKEN}
