# We need xenial otherwise we will get an ssl error with tornado install
dist: xenial
sudo: required
language: generic
branches:
    only:
    - /.*/
addons:
    apt:
        packages:
            - texlive-full
script:
    - latexmk
    - git checkout -b deploy
    - git add main.pdf
    - git commit -m "Updating main.pdf at `date`"
