dist: xenial
language: python
cache: pip
python:
- '3.6'
branches:
  only:
  - "/.*/"
addons:
  apt:
    packages:
    - pandoc
install:
- pandoc -v
- pip install -r requirements.txt
script:
- echo "Hello"
before_deploy:
- openssl aes-256-cbc -K $encrypted_0a73d3c4e754_key -iv $encrypted_0a73d3c4e754_iv
  -in deploy_wiki.enc -out /tmp/deploy_wiki -d
- openssl aes-256-cbc -K $encrypted_0a73d3c4e754_key -iv $encrypted_0a73d3c4e754_iv
  -in deploy_site.enc -out /tmp/deploy_site -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_wiki
- chmod 600 /tmp/deploy_site
- export NUM_RETRIES=3
- export BUILD_TIME=10
- export CLONE_DIR=`mktemp -d`
deploy:
  provider: script
  script: bash _scripts/push_to_wiki.sh
  skip_cleanup: true
  on:
    branch: master
