dist: trusty
sudo: false
language: generic
branches:
    only:
    - /.*/
addons:
    apt:
        packages:
            - texlive-full
script:
    - make
    - git checkout -b deploy
    - git add main.pdf
    - git commit -m "Updating main.pdf at `date`"
