dist: xenial
sudo: false
language: python
cache: pip
python:
- '3.6'
branches:
  only:
  - "/.*/"
addons:
  apt:
    packages:
    - pandoc
install:
- pandoc -v
- pip install -r requirements.txt
before_deploy:
- openssl aes-256-cbc -K $encrypted_0a73d3c4e754_key -iv $encrypted_0a73d3c4e754_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- echo 1 #git checkout -b deploy
- test $TRAVIS_BRANCH = "master" && bash _scripts/push_to_wiki.sh ${GITHUB_TOKEN}
